// screens.jsx — screen registry. ctx = { go, openModal, plan, activeTemplate }
window.SCREENS = {
  landing: (c) => <LandingScreen go={c.go} />,
  faq: (c) => <FaqScreen go={c.go} />,
  contact: (c) => <ContactScreen go={c.go} />,
  docs: (c) => <DocsScreen go={c.go} />,
  apropos: (c) => <AProposScreen go={c.go} />,
  blog: (c) => <BlogScreen go={c.go} />,
  carrieres: (c) => <CarrieresScreen go={c.go} />,
  dashboard: (c) => <DashboardScreen go={c.go} openModal={c.openModal} />,
  portfolios: (c) => <PortfoliosScreen go={c.go} openModal={c.openModal} />,
  nfc: (c) => <NFCScreen go={c.go} openModal={c.openModal} />,
  formules: (c) => <FormulesScreen go={c.go} openModal={c.openModal} />,
  profil: (c) => <ProfilScreen go={c.go} openModal={c.openModal} />,
  analytics: (c) => <AnalyticsScreen go={c.go} />,
  portfolio: (c) => <PortfolioScreen onBack={() => c.go('dashboard')} template={c.activeTemplate} />,
  business: (c) => <BusinessDashboardScreen go={c.go} openModal={c.openModal} />,
  'business-members': (c) => <BusinessMembersScreen go={c.go} openModal={c.openModal} />,
  'business-join': (c) => <BusinessJoinScreen go={c.go} />,
  'business-portfolios': (c) => <BusinessDashboardScreen go={c.go} openModal={c.openModal} />,
  'business-analytics': (c) => <BusinessDashboardScreen go={c.go} openModal={c.openModal} />,
  // ── Admin ──
  admin: (c) => <AdminDashboardScreen go={c.go} />,
  'admin-clients': (c) => <AdminClientsScreen go={c.go} />,
  'admin-wave': (c) => <AdminWaveScreen go={c.go} />,
  'admin-finance': (c) => <AdminFinanceScreen go={c.go} />,
  'admin-paiements': (c) => <AdminPaiementsScreen go={c.go} />,
  'admin-team': (c) => <AdminTeamScreen go={c.go} />,
  'admin-portfolios': (c) => <AdminModuleScreen go={c.go} screen="admin-portfolios" />,
  'admin-factures': (c) => <AdminModuleScreen go={c.go} screen="admin-factures" />,
  'admin-formules': (c) => <AdminModuleScreen go={c.go} screen="admin-formules" />,
  'admin-upgrades': (c) => <AdminModuleScreen go={c.go} screen="admin-upgrades" />,
  'admin-stats': (c) => <AdminModuleScreen go={c.go} screen="admin-stats" />,
  'admin-blog': (c) => <AdminModuleScreen go={c.go} screen="admin-blog" />,
  'admin-pages': (c) => <AdminModuleScreen go={c.go} screen="admin-pages" />,
};
