// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khlhwrxgytgzjcquuvoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobGh3cnhneXRnempjcXV1dm9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTExNDYsImV4cCI6MjA2NjY4NzE0Nn0.GifAF3BAwnp0JM7ifOO8QHMmYFtZA5qFZJGO5BkMyss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);